### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Huanle** [JensUweUlrich/ReadBouncer#36]
Hi @JensUweUlrich ,

thanks a lot for developing readbouncer.

I was trying to compile following the *compilation on linux* instruction. 
I ran into errors at the 1st config stage. 
```
$ cmake --build . --config Release
Consolidate compiler generated dependencies of target interfaces
[  0%] Built target interfaces
[  0%] Building CXX object IBF/CMakeFiles/IBF.dir/IBFBuild.cpp.o
In file included from /home/test/lhl/sw/ReadBouncer/src/IBF/IBF.hpp:3:0,
                 from /home/test/lhl/sw/ReadBouncer/src/IBF/IBFBuild.cpp:2:
/home/test/lhl/sw/ReadBouncer/src/IBF/IBFConfig.hpp:9:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
IBF/CMakeFiles/IBF.dir/build.make:75: recipe for target 'IBF/CMakeFiles/IBF.dir/IBFBuild.cpp.o' failed
make[2]: *** [IBF/CMakeFiles/IBF.dir/IBFBuild.cpp.o] Error 1
CMakeFiles/Makefile2:957: recipe for target 'IBF/CMakeFiles/IBF.dir/all' failed
make[1]: *** [IBF/CMakeFiles/IBF.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
```
Can you please help to sort it out what's going wrong?
Thanks heaps in advance.

**Comment by JensUweUlrich** [comment]
Hi @Huanle,

thanks for your message and your interest in using ReadBouncer. 

Could you please tell me which compiler and compiler version you are using. It seems like you tried to build ReadBouncer with an older compiler that is missing std::filesystem. I recommend using gcc-9 and later. 
BTW: We also provide precompiled binaries for linux to avoid running into compilation (and linking) errors.

Best
Jens

**Comment by Huanle** [comment]
Hi @JensUweUlrich ,

thanks a lot for your prompt reply. I was using the following compliler. 
> gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
cmake version 3.21.0

I will give gcc-9 a go.

**Comment by JensUweUlrich** [comment]
Ok. `std::filesystem` is not supported in gcc-7. I will add gcc-8 or later as a requirement to the readme.

Don't hesitate to get back to me if you run into further troubles.

**Comment by Huanle** [comment]
Hi 
Hi @JensUweUlrich,

Thanks a lot for your kindness. 
I just ran into a new error after upgrading gcc7 to gcc8. It seems to be close to success though :-) 

>
gcc --version 
gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0


>
[ 95%] Building CXX object minknow/CMakeFiles/ReadUntil.dir/Acquisition.cpp.o
[ 95%] Building CXX object minknow/CMakeFiles/ReadUntil.dir/Analysis_Configuration.cpp.o
[ 95%] Building CXX object minknow/CMakeFiles/ReadUntil.dir/Data.cpp.o
In file included from /home/test/lhl/sw/ReadBouncer/src/minknow/Data.hpp:36,
                 from /home/test/lhl/sw/ReadBouncer/src/minknow/Data.cpp:8:
/home/test/lhl/sw/ReadBouncer/build/minknow/stduuid/include/uuid.h:20:10: fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
          ^~~~~~~~~~~~~
compilation terminated.
minknow/CMakeFiles/ReadUntil.dir/build.make:298: recipe for target 'minknow/CMakeFiles/ReadUntil.dir/Data.cpp.o' failed
make[2]: *** [minknow/CMakeFiles/ReadUntil.dir/Data.cpp.o] Error 1
CMakeFiles/Makefile2:1077: recipe for target 'minknow/CMakeFiles/ReadUntil.dir/all' failed
make[1]: *** [minknow/CMakeFiles/ReadUntil.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JensUweUlrich** [comment]
Hi @Huanle 

that looks weird. Seems like CMake did not set the include path for `stduuid` correctly. I sucessfully built ReadBouncer with gcc-8 today. I would suggest to delete everything within your `build` directory and repeat the entire build workflow with the following comands:

```
cmake ../src/
cmake --build . --config Release
cmake --build . --config Release --target package
```
Cheers
Jens

**Comment by Huanle** [comment]
Thanks a lot @JensUweUlrich for your advice.

I deleted the `build` folder and then repeated the processes. 
This time it proceeded further before it failed again. 

> ......
[ 97%] Generating minknow/proto/minknow_api/rpc_options.pb.cc, minknow/proto/minknow_api/rpc_options.pb.h, minknow/proto/minknow_api/rpc_options.grpc.pb.cc, minknow/proto/minknow_api/rpc_options.grpc.pb.h
[ 97%] Building CXX object minknow/CMakeFiles/ReadUntil.dir/Acquisition.cpp.o
[ 97%] Building CXX object minknow/CMakeFiles/ReadUntil.dir/Analysis_Configuration.cpp.o
[ 97%] Building CXX object minknow/CMakeFiles/ReadUntil.dir/Data.cpp.o
In file included from /home/test/lhl/sw/ReadBouncer/src/minknow/Data.hpp:36,
                 from /home/test/lhl/sw/ReadBouncer/src/minknow/Data.cpp:8:
/home/test/lhl/sw/ReadBouncer/build/minknow/stduuid/include/uuid.h:20:10: fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
          ^~~~~~~~~~~~~
compilation terminated.
minknow/CMakeFiles/ReadUntil.dir/build.make:298: recipe for target 'minknow/CMakeFiles/ReadUntil.dir/Data.cpp.o' failed
make[2]: *** [minknow/CMakeFiles/ReadUntil.dir/Data.cpp.o] Error 1
CMakeFiles/Makefile2:1077: recipe for target 'minknow/CMakeFiles/ReadUntil.dir/all' failed
make[1]: *** [minknow/CMakeFiles/ReadUntil.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JensUweUlrich** [comment]
Hi @Huanle 

I guess I know what's going on here. Could you try to install uuid with the following statements?:
```
apt install uuid-dev
```
I expect this will solve the issue.

**Comment by JensUweUlrich** [comment]
Hi @Huanle 

I pushed some changes to the master branch that should fix the problem. Again, I recommend to make a clean build.

Cheers
Jens

**Comment by Huanle** [comment]
Hi @JensUweUlrich ,

thanks a lot!
This time, I re-cloned the git repo and repeat the installation commands. The error message remains.

```        
/home/test/lhl/sw/ReadBouncer/src/main/main.cpp: In function ‘std::vector<interleave::IBFMeta> getIBF(ConfigReader, bool, bool)’:
/home/test/lhl/sw/ReadBouncer/src/main/main.cpp:312:52: warning: control reaches end of non-void function [-Wreturn-type]
  std::vector<interleave::IBFMeta> DepletionFilters{};
                                                    ^
[100%] Linking CXX executable ReadBouncer
../basecaller/Guppy/libGuppyCppClient_gcc-8.a(operations.o): In function `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, unsigned int, boost::system::error_code*)':
operations.cpp:(.text+0x382): undefined reference to `statx'
operations.cpp:(.text+0x561): undefined reference to `statx'
../basecaller/Guppy/libGuppyCppClient_gcc-8.a(operations.o): In function `boost::filesystem::detail::copy_directory(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)':
operations.cpp:(.text+0x71c): undefined reference to `statx'
../basecaller/Guppy/libGuppyCppClient_gcc-8.a(operations.o): In function `boost::filesystem::detail::equivalent(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)':
operations.cpp:(.text+0x18b1): undefined reference to `statx'
operations.cpp:(.text+0x18e4): undefined reference to `statx'
../basecaller/Guppy/libGuppyCppClient_gcc-8.a(operations.o):operations.cpp:(.text+0x196c): more undefined references to `statx' follow
collect2: error: ld returned 1 exit status
main/CMakeFiles/ReadBouncer.dir/build.make:149: recipe for target 'main/ReadBouncer' failed
make[2]: *** [main/ReadBouncer] Error 1
CMakeFiles/Makefile2:5485: recipe for target 'main/CMakeFiles/ReadBouncer.dir/all' failed
make[1]: *** [main/CMakeFiles/ReadBouncer.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by JensUweUlrich** [comment]
Hi @Huanle 

That was a different kind of error. Your system kernel doesn't support statx system calls, that are used by Boost, which is part of our precompiled GuppyClientLib. I upgraded the GuppyClientLib to use Boost-1.77 with the usage of statx system calls as describd [here](https://github.com/boostorg/filesystem/issues/172). Please update your repository before trying to build again. I hope this fixes your problem.

**Comment by JensUweUlrich** [comment]
The libGuppyCppClient_linux_x86_64.tar.gz was corrupted. I uploaded it again.

**Comment by Huanle** [comment]
Hi @JensUweUlrich ,
Many many thanks. It's been successfully compiled.
