### ISSUE TITLE
[Error] Could not find DeepNano weights file - but I am using Guppy

### ISSUE THREAD

**Issue by JWDebler** [JensUweUlrich/ReadBouncer#37]
Hi,

I am trying to run a simulation test, but keep getting this error, even though I have "Guppy" as my basecaller in my config file.

I downloaded the precompiled linux version.

my config.toml looks like this:

```
usage               = "target"
output_directory    = '/home/johannes/ReadBouncer/output_dir/'
log_directory       = '/home/johannes/ReadBouncer/'

[IBF]

kmer_size           = 13                      
fragment_size       = 100000                  
threads             = 3                      
target_files        = ['/home/johannes/ReadBouncer/chm13.v1.1_chr21_22.fasta']
deplete_files       = ['/home/johannes/ReadBouncer/chm13.v1.1_chr1-20_XM.fasta']  
exp_seq_error_rate  = 0.1                      
             

[MinKNOW]

host                = "localhost"
port                = 9501       
flowcell            = "MS00000" 

[Basecaller]

caller             = "Guppy"
host               = "127.0.0.1"
port               = 5555  
```

I'm calling it like this:
`johannes@nanopore:~/Downloads/ReadBouncer-1.1.0-Linux/bin$ ./ReadBouncer config.toml `

And I am getting this output:

```
Calculated size of the IBF : 150.912 MBytes
IBF-build processed 2 sequences (96.4156 Mbp) in 6.49807 seconds (0.018467 Kseq/m, 890.255 Mbp/m)
 - 2 sequences in 965 bins were written to the IBF
Calculated size of the IBF : 4367.01 MBytes
IBF-build processed 22 sequences (2958.42 Mbp) in 287.524 seconds (0.00459092 Kseq/m, 617.357 Mbp/m)
 - 22 sequences in 29596 bins were written to the IBF
[Error] Could not find DeepNano weights file : ./ReadBouncer/data/rnn48.txt
Real time : 313.928 sec
CPU time  : 313.125 sec
Peak RSS  : 8960 MByte

```

Any idea what might be going on?

Cheers,
Johannes

**Comment by JensUweUlrich** [comment]
Hi @JWDebler 

thanks for raising the issue and your interest in ReadBouncer.

I guess the problem relates to your config.toml. First, please indicate the port numbers as strings, e.g. `port = "5555"`. We will do some improvements in the near future that will also allow to specify port numbers without quotation marks. 

However, the main issue here is, that you didn't state the config file for the guppy basecaller. Using e.g. `config = "dna_r9.4.1_450bps_fast"` is crucial to instantiate the guppy basecall client. You will also need to run a guppy basecall server on a GPU on your basecall host (127.0.0.1 in your case) to do guppy basecalling. If you don't have a GPU, we recommend to use DeepNano for basecalling instead.

Cheers
Jens

**Comment by JWDebler** [comment]
Hi @JensUweUlrich ,

I am one step closer. I got it working. The problem seemed to be that I was running ReadBouncer from within its bin directory.

`johannes@nanopore:~/Downloads/ReadBouncer-1.1.0-Linux/bin$ ./ReadBouncer config.toml `

First I changed the config as you suggested and it failed as before.

Then I went out of the ReadBounder folder structure and ran again:

`johannes@nanopore:~/Downloads$ ReadBouncer-1.1.0-Linux/bin/ReadBouncer ReadBouncer-1.1.0-Linux/bin/config.toml 
`
It is working and I can see reads clustering as in the screenshot in your Readme.
However, I am now running into this problem about 15 minutes into the simulated run:
```
johannes@nanopore:~/Downloads$ ReadBouncer-1.1.0-Linux/bin/ReadBouncer ReadBouncer-1.1.0-Linux/bin/config.toml 
965 bins were loaded in 0.0473665 seconds from the IBF
29596 bins were loaded in 1.3704 seconds from the IBF
Trying to connect to MinKNOW
Host : localhost
Port : 9501
Connection successfully established!
Waiting for device to start sequencing!
Please start the sequencing run now!
Sequencing has begun. Starting live signal processing!
[2022-02-24 09:45:02.213061] [0x00007f2913fff700] [info]    Connecting to server as ''
[2022-02-24 09:45:02.213958] [0x00007f2913fff700] [info]    Connected to server as ''. Connection id: 5871f532-baa3-400f-a42f-687e3572e1fc
Start receiving live signals thread
Start basecalling thread
Start read classification thread
Start sending unblock messages thread
Segmentation fault (core dumped)
```

**Comment by JensUweUlrich** [comment]
Hi @JWDebler 

Could you provide me with the output files, log files and your config.toml file? You can zip them and send to jens-uwe.ulrich@hpi.de. That makes debugging easier for me. 

Thanks
Jens

**Comment by JensUweUlrich** [comment]
Hi @JWDebler 

Thanks for sending me the log files. Although they were not that useful, I was lucky to reproduce the seg fault. This was a little bug related to the management of already seen reads and I fixed it immediately. I updated the Linux binaries as well, so that you can retry to test with the playback run. 

Cheers
Jens

**Comment by JWDebler** [comment]
Excellent news! I'll try it first thing Monday morning. Thanks.

**Comment by JensUweUlrich** [comment]
Sorry, I just forgot to update the Readme.md

Cheers
