### ISSUE TITLE
Make error while installing ReadBouncer

### ISSUE THREAD

**Issue by merfre** [JensUweUlrich/ReadBouncer#42]
Hello,

I am trying to install ReadBouncer on an Ubuntu 20.04 machine and have run into an error that I cannot fix. I followed your instructions, got all the dependencies listed and followed the instructions for compilation on Linux. The first 5 lines ran perfectly fine, but when I ran the second cmake line I got a strange error (pasted below) that I do not know how to fix. I tried updating all my software, reinstalling my c++ compiler, to delete it all and start over again, etc. Do you know how I might solve this? Thanks in advance!

merfre@BioRig2:~/ReadBouncer/build$ cmake --build . --config Release
[ 95%] Built target interfaces
[ 95%] Built target IBF
[ 95%] Built target DeepNano
[ 95%] Built target Guppy
[ 95%] Built target zlibstatic
[ 95%] Built target address_sorting
[ 95%] Built target absl_log_severity
[ 95%] Built target absl_raw_logging_internal
[ 95%] Built target absl_bad_optional_access
[ 95%] Built target absl_spinlock_wait
[ 95%] Built target absl_base
[ 95%] Built target absl_malloc_internal
[ 95%] Built target absl_throw_delegate
[ 95%] Built target absl_debugging_internal
[ 95%] Built target absl_stacktrace
[ 95%] Built target absl_strings_internal
[ 95%] Built target absl_demangle_internal
[ 95%] Built target absl_int128
[ 95%] Built target absl_strings
[ 95%] Built target absl_symbolize
[ 95%] Built target absl_str_format_internal
[ 95%] Built target absl_cord
[ 95%] Built target absl_status
[ 95%] Built target absl_graphcycles_internal
[ 95%] Built target absl_time_zone
[ 95%] Built target absl_civil_time
[ 95%] Built target absl_time
[ 95%] Built target absl_synchronization
[ 95%] Built target gpr
[ 95%] Built target upb
[ 95%] Built target absl_exponential_biased
[ 95%] Built target absl_hashtablez_sampler
[ 95%] Built target absl_raw_hash_set
[ 95%] Built target absl_bad_variant_access
[ 95%] Built target absl_city
[ 95%] Built target absl_hash
[ 95%] Built target absl_statusor
[ 95%] Built target c-ares
[ 95%] Built target re2
[ 95%] Built target crypto
[ 95%] Built target ssl
[ 95%] Built target grpc
[ 95%] Built target libprotobuf
[ 95%] Built target grpc++
[ 95%] Built target libprotoc
[ 95%] Built target grpc_plugin_support
[ 95%] Built target grpc_cpp_plugin
[ 95%] Built target protoc
Consolidate compiler generated dependencies of target ReadUntil
[ 95%] Building CXX object minknow/CMakeFiles/ReadUntil.dir/Manager.cpp.o
/home/merfre/ReadBouncer/src/minknow/Manager.cpp: In member function ‘uint32_t readuntil::Manager::getRpcPort(minknow_api::manager::FlowCellPosition&)’:
/home/merfre/ReadBouncer/src/minknow/Manager.cpp:53:27: error: ‘const class minknow_api::manager::FlowCellPosition_RpcPorts’ has no member named ‘insecure’; did you mean ‘secure’?
   53 |    return dev.rpc_ports().insecure();
      |                           ^~~~~~~~
      |                           secure
/home/merfre/ReadBouncer/src/minknow/Manager.cpp: In member function ‘std::string readuntil::Manager::getGuppyVersion()’:
/home/merfre/ReadBouncer/src/minknow/Manager.cpp:71:3: error: ‘GetVersionInfoResponse’ was not declared in this scope; did you mean ‘minknow_api::instance::GetVersionInfoResponse’?
   71 |   GetVersionInfoResponse response;
      |   ^~~~~~~~~~~~~~~~~~~~~~
      |   minknow_api::instance::GetVersionInfoResponse
In file included from /home/merfre/ReadBouncer/build/minknow/minknow/proto/minknow_api/manager.pb.h:40,
                 from /home/merfre/ReadBouncer/build/minknow/minknow/proto/minknow_api/manager.grpc.pb.h:7,
                 from /home/merfre/ReadBouncer/src/minknow/Manager.hpp:11,
                 from /home/merfre/ReadBouncer/src/minknow/Manager.cpp:14:
/home/merfre/ReadBouncer/build/minknow/minknow/proto/minknow_api/instance.pb.h:520:7: note: ‘minknow_api::instance::GetVersionInfoResponse’ declared here
  520 | class GetVersionInfoResponse PROTOBUF_FINAL :
      |       ^~~~~~~~~~~~~~~~~~~~~~
/home/merfre/ReadBouncer/src/minknow/Manager.cpp:73:64: error: ‘response’ was not declared in this scope
   73 |   ::grpc::Status status = stub->get_version_info(&c, request, &response);
      |                                                                ^~~~~~~~
make[2]: *** [minknow/CMakeFiles/ReadUntil.dir/build.make:354: minknow/CMakeFiles/ReadUntil.dir/Manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1078: minknow/CMakeFiles/ReadUntil.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by JensUweUlrich** [comment]
Hi @merfre 

Thanks for your interest in ReadBouncer.

I think the issue originates from the new MinKNOW API version, that was released some days ago. As long as you are using the MinKNOW version 4.5.0, you can use the prebuild binaries from [here](https://github.com/JensUweUlrich/ReadBouncer/releases/tag/v1.1.1). I also did a quick fix on the ReadBouncer branches to use only version 4.5.0 of the minknow_api which should fix the error message. 

At the moment, we do not support the latest MinKNOW 5.0.0 release. But I will provide support with the next minor Release.

Cheers
Jens

**Comment by merfre** [comment]
Hello @JensUweUlrich 

I deleted what I had and started over again - it worked! Thank you very much for your swift reply and fix.
