### ISSUE TITLE
TOML File Key in README Incorrect 

### ISSUE THREAD

**Issue by syncrotron** [JensUweUlrich/ReadBouncer#45]
Through attempting to get ReadBouncer up and running with a custom TOML file, I noticed that within the readme file ["Building the database"](https://github.com/JensUweUlrich/ReadBouncer/blob/master/README.md#building-the-database) section the TOML key `output_dir` is referenced. If a TOML is provided to Breadboard with this key, the following error is provided:
```
Error in /my/home/path/readboucer_conf.toml
[error] key "output_directory" not found in the top-level table
 --> /path/to/config/readboucer_conf.toml
   |
 1 | usage         = "build"
   | ^--- the top-level table starts here
```
The reference `output_dir` instead of `output_directory` as a TOML key appears to be an error.

**Comment by JensUweUlrich** [comment]
Thanks for pointing that out. That's an error in the documentation. The parameter should be `output_directory`. I will change that immediately in the documentation.
