### ISSUE TITLE
Unable to build ReadBouncer

### ISSUE THREAD

**Issue by maximilianmordig** [JensUweUlrich/ReadBouncer#47]
Hi

I have a problem with building ReadBouncer. Here is the error I get after executing
`cmake ../src` as per the README:
```
CMake Error at cmake/protobuf.cmake:58 (find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:254 (include)

```
On `cmake version 3.20.3`.
I am not very familiar with `cmake`. I cannot find the file `cmake/protobuf.cmake`
I also searched on Google for `find_package(Protobuf REQUIRED)`, but didn't find anything useful.

Do you know how to solve this issue?

Thanks in advance.

**Comment by lutfia95** [comment]
Hi @maximilianmordig, 

sorry for the late answer, can you please try to install `uuid` and `uuid-dev` by `sudo apt install uuid uuid-dev`?. I would suggest deleting everything within your build directory and repeat the entire build process again after installing `uuid` and `uuid-dev`. You can also use the prebuild binaries from [here](https://github.com/JensUweUlrich/ReadBouncer/releases/tag/v1.1.1) until we solve the issue.

Best,
Ahmad
