### ISSUE TITLE
How to use ReadBouncer on a playback run made of multiple bulk fast5 files ?

### ISSUE THREAD

**Issue by virhostnet** [JensUweUlrich/ReadBouncer#53]
Dear ReadBouncer team,

We have generated a multiple bulk fast5 files run (~200Go, 4000 reads per file) on MK1C (all Bulk output items selected) and would like to test ReadBouncer on a playback run.

Is it possible to playback the run on this data structure? Simulation seems to accept only path to a single bulk fast5 file not a directory of files ?

Thanks by advance,

Cheers

Vincent

**Comment by JensUweUlrich** [comment]
Would you mind sharing the bulk fast5 file with me? It's hard to find such raw data and I'm always looking for data sets that help me improve ReadBouncer.

**Comment by virhostnet** [comment]
We will be pleased to share this bulk file that we are currently producing with you (we did not keep the single bulk files last time, only multifast5 files which do not contain enough information for playback). This can be done in a context of a scientific collaboration. We can discusse about that in private mail as it invloved other collaborators ? Cheers

**Comment by JensUweUlrich** [comment]
@virhostnet 
I'm always open for collaborations. You can contact me via jens-uwe.ulrich@hpi.de to further discuss potential projects.
Cheers
Jens
