### ISSUE TITLE
Dorado basecaller

### ISSUE THREAD

**Issue by JensUweUlrich** [JensUweUlrich/ReadBouncer#56]
add support for basecalling with [Dorado](https://github.com/nanoporetech/dorado)

**Comment by ASTR44** [comment]
Hi, I am really interested in trying your tool but we have MinKNOW set up with dorado basecalling so I was wondering if you had any plans for when you will ad support for it?

**Comment by JensUweUlrich** [comment]
Hi, unfortunately ONT does not make the basecall_server code for Dorado publicly available, and thus I'm not able to support Dorado for live-basecalling. I'm sorry to say that, but Guppy 6.4 is the last basecaller version I will support.
