### ISSUE TITLE
ReadBouncer no connecting to MinKnow properly 

### ISSUE THREAD

**Issue by edidah** [JensUweUlrich/ReadBouncer#59]
Hi Jens Uwe, I got an issue connecting the ReadBouncer to the Minknow as shown in the screenshot attached while using the provided chromosome dataset. Any advice on this issue will be of much help. 

Thank you
Moraa
<img width="822" alt="Screenshot 2022-10-21 at 15 22 41" src="https://user-images.githubusercontent.com/44297932/197195263-10358ce3-98d9-4d29-b3e9-167db46498de.png">
<img width="1145" alt="Screenshot 2022-10-21 at 15 24 09" src="https://user-images.githubusercontent.com/44297932/197195270-63dc5b4e-c411-49a9-ab3d-ed6c082d761a.png">

**Comment by JensUweUlrich** [comment]
Hi @edidah 

Is there a specific reason why you are trying to connect to MinKNOW using port 9505? If not, then please try to use port 9502, which is the dfeualt port for a secure connection to MinKNOW.

**Comment by edidah** [comment]
Hi JensUweUlrich,

Thanks for the prompt feedback. We initially tried connecting to the port
'9502' but it keeps failing with an error message; cannot connect to the
given host and port addresses. But works fine with port 9504 and 8001/4.
Thanks

**Comment by edidah** [comment]
Hi Jens, 
I am still stuck on the simulated device. We have installed the ReadBouncer on GridION device which runs MinKnow. Is the simulated device a virtual machine beside the GridION? And do you have guidelines to setup the simulated device?
