### ISSUE TITLE
readbouncer cannot connect to minKNOW

### ISSUE THREAD

**Issue by willros** [JensUweUlrich/ReadBouncer#62]
Hi,

I get the following message when trying to run ReadBouncer:
```
965 bins were loaded in 0.0445678 seconds from the IBF
29596 bins were loaded in 1.26652 seconds from the IBF
Trying to connect to MinKNOW
Host : localhost
Port : 9502
failed to connect to all addresses
Real time : 4.15342 sec
CPU time  : 4.14012 sec
Peak RSS  : 8896 MByte
```
I am using the latest ReadBouncer for linux x86. 
I am using minKNOW 22.10.7 with
MinKNOW core:
5.3.1
Guppy:
6.3.8
Bream:
7.3.2
Script Configuration:
5.3.7

The minknow daemon is up and running, controlled by:
```bash
systemctl status minknow.service
```

The config.toml file:
```bash
usage               = "target"
output_directory    = '/home/nanopore/setting-up-adaptive-sampling/test-readbouncer'
log_directory       = '/home/nanopore/setting-up-adaptive-sampling/test-readbouncer/log'

[IBF]

kmer_size           = 13                      
fragment_size       = 100000                  
threads             = 3                      
target_files        = ['/home/nanopore/setting-up-adaptive-sampling/test-readbouncer/chm13.v1.1_chr21_22.ibf']
deplete_files       = ['/home/nanopore/setting-up-adaptive-sampling/test-readbouncer/chm13.v1.1_chr1-20_XM.ibf']  
exp_seq_error_rate  = 0.1                      
             

[MinKNOW]

host                = "localhost"
port                = "9502"       
flowcell            = "MS00000" 

[Basecaller]

caller             = "DeepNano"  
threads            = 3         
```

Any idea what I can try or what is going on?

Thanks a lot,
William

**Comment by JensUweUlrich** [comment]
Hi @willros 

It seems that ReadBouncer cannot connect to the given flowcell port. Did you set up the simulated device `MS00000` in MinKNOW?

**Comment by willros** [comment]
Hi @JensUweUlrich

Yes, I set up the simulated device `MS0000` as instructed in your github repo. 
I also did not change the default value for the ports for `guppy` and `minKNOW`. 

I can see the simulated the devide in minKNOW and start a dry run inside there, but readbouncer is not able to connect.

**Comment by JensUweUlrich** [comment]
Just to be sure we don't miss anything: Are you running MinKNOW and ReadBouncer on the same machine? And you have installed the latest ReadBouncer version (version 1.2.2)?

**Comment by willros** [comment]
Hi,

I was running version 1.1 (from the master branch). I will try to download the latest and see if it works. Thank you!

**Comment by JensUweUlrich** [comment]
Ah ok, that's probably the issue. ReadBouncer 1.1 is not compatible with MinKNOW 5.x. Using the latest ReadBouncer version should solve your problem.

**Comment by willros** [comment]
Thanks yet again. Now I am running ReadBouncer exactly as you describe in your example for playback experiment.

Just one more related question; approximately how long will it take until it finishes, using the DeepNano caller?

William

**Comment by JensUweUlrich** [comment]
That doesn't depend on the base caller. When the sequencing run has finished or has been stopped by the user via MinKNOW, ReadBouncer will also stop running.

**Comment by JensUweUlrich** [comment]
@jamesemery 
Which versions of MinKNOW and ReadBouncer are you using?

**Comment by jamesemery** [comment]
I found that switching to Read bouncer 1.2 fixed this issue, I just fell into the trap of downloading the wrong version from the README. MinKNOW 22.08.9
