### ISSUE TITLE
failed to connect to all addresses

### ISSUE THREAD

**Issue by kcleal** [JensUweUlrich/ReadBouncer#63]
Hi,
Im having trouble connecting to Minknow (on my local machine) and get this log message:

    -1.2.2-Linux/bin/ReadBouncer --config config.16p1_21q.toml
    IBF-build processed 2 sequences (0.000134 Mbp) in 0.00407432 seconds (29.4528 Kseq/m, 1.97333 Mbp/m)
     - 2 sequences in 2 bins were written to the IBF
    Trying to connect to MinKNOW
    Host : localhost
    Port : 9502
    Connecting to MinKNOW using the token: 44c5fc5d-f61b-4b1a-a00f-114bdbc6d90b
    failed to connect to all addresses
    Real time : 0.0420797 sec
    CPU time  : 0.030172 sec
    Peak RSS  : 31 MByte

Is the token wrong?
I tried using port 9504, but no luck. Im using Minkow GUI 5.3.6, ReadBouncer 1.2.2, ubuntu.

Thanks!

**Comment by JensUweUlrich** [comment]
Hi @kcleal 

To which device/flowcell are you trying to connect? Did you setup a simulated device in MinKNOW?

**Comment by kcleal** [comment]
It was a minion mk1b. It was using an old flow cell in live mode

**Comment by JensUweUlrich** [comment]
Did you check that the name of that flowcell was correctly specified in the config.TOML file?

**Comment by kcleal** [comment]
Sorry I think I was using the wrong name. The 'Position' appears to work but not the 'Flow cell ID'

![Screenshot from 2022-12-16 13-44-04](https://user-images.githubusercontent.com/42997789/208112127-d0a6c88e-1447-4e25-9bd2-5706c77bf615.png)
