### ISSUE TITLE
 [timed_out] Timeout waiting for reply to request: LOAD_CONFIG

### ISSUE THREAD

**Issue by kcleal** [JensUweUlrich/ReadBouncer#64]
Hi,

ReadBouncer keeps throwing this error whenever I start a sequencing run. Im using an old flow cell in live sequencing mode - it only has a few active pores, could this be a problem?

        IBF-build processed 2 sequences (0.000134 Mbp) in 0.00224295 seconds (53.5011 Kseq/m, 3.58457 Mbp/m)
         - 2 sequences in 2 bins were written to the IBF
        Trying to connect to MinKNOW
        Host : localhost
        Port : 9502
        Connecting to MinKNOW using the token: 7d2c7e22-bbfb-43b8-9d37-69fb6f90cf40
        Connection successfully established!
        Waiting for device to start sequencing!
        Please start the sequencing run now!
        Sequencing has begun. Starting live signal processing!
        Connecting to Guppy basecall server on address : 127.0.0.1:9502
        [guppy/error] basecall_service::BasecallClient::worker_loop: Connection error. [timed_out] Timeout waiting for reply to request: LOAD_CONFIG
        [timed_out] Timeout waiting for reply to request: LOAD_CONFIG
        Real time : 32.0663 sec
        CPU time  : 0.114984 sec
        Peak RSS  : 30 MByte

My config file is:

        [IBF]
        kmer_size          = 15         #(unsigned integer with default 13) only required for 'usage = "build"' or if target_file/deplete_file is a fasta formate file 
        fragment_size      = 100000     #(unsigned integer with default 100000)  only required for 'usage = "build" or if target_file/deplete_file is a fasta formate file 
        threads            = 3          #(unsigned integer with default 3)
        target_files  = ['/home/alex/Desktop/AdaptiveSampling/ref_seqs/16p1_21q.fasta']
        deplete_files = []
        #read_files    = ['path/to/read/file/SampleZMCDataSet.fasta']
        exp_seq_error_rate = 0.1        #(unsigned float between 0 and 1 default 0.1)
        chunk_length       = 360        #(unsigned integer with default 250)
        max_chunks         = 1          #(unsigned integer with default 5)
        
        
        [MinKNOW]
        host               = "localhost" #(ip address or name of the computer hosting MinKNOW)
        port               = "9502"      #(port number used fo grpc communication by by MinKNOW instance) 
        flowcell           = "MN42383"   #(name of the flowcell used)
        channels           = [1,512]
        
        
        [Basecaller]
        caller             = "Guppy" #DeepNano/Guppy (default is DeepNano)
        host               = "127.0.0.1"#(ip address or name of the computer hosting Guppy Basecall Server)
        port               = "9502"     #(port number on which the basecall server is running on the host)
        threads            = 3          # (unsigned integer with default 3)
        config             = "dna_r9.4.1_450bps_fast"

**Comment by JensUweUlrich** [comment]
I think you are using the wrong port for the basecaller here. On which host are you running the guppy_basecall_server? If you did not start a separate server instance, you should state the following. 
```
[Basecaller]
caller = "Guppy"
host = "/tmp/.guppy"
port = "5555"
config = "dna_r9.4.1_450bps_fast"
```

**Comment by kcleal** [comment]
Hi,
Thanks for the quick response. Im using my local machine - sequencing on the same machine as readbouncer.  I will try this!

**Comment by kcleal** [comment]
It got passed that error, but I have a new zeromq error:

        Connecting to Guppy basecall server on address : /tmp/.guppy:5555
        [guppy/error] basecall_service::BasecallClient::worker_loop: Connection error. [failed] zmq::error_t : Invalid argument
        [failed] zmq::error_t : Invalid argument
        Real time : 311.907 sec
        CPU time  : 0.11749 sec
        Peak RSS  : 31 MByte

**Comment by JensUweUlrich** [comment]
Ah..sorry. That was my fault. Try this one:
```
[Basecaller]

caller             = "Guppy"  
host 		   = "ipc:///tmp/.guppy"
port               = "5555"
config		   = "dna_r9.4.1_450bps_fast"
```

**Comment by kcleal** [comment]
Im still getting the same error unfortunately. The config file looks like:

      [Basecaller]
      caller             = "Guppy"
      host = "ipc:///tmp/.guppy"
      port = "5555"
      threads            = 3
      config             = "dna_r9.4.1_450bps_fast"
  
The output was:

      (base) alex@alex-ISRMOT-235:~/Desktop/AdaptiveSampling/experiments/Harsh_15.12.22/rbas$ ~/Desktop/AdaptiveSampling/software/ReadBouncer-1.2.2-Linux/bin/ReadBouncer --config ~/Desktop/AdaptiveSampling/experiments/Harsh_15.12.22/config.16p1_21q.toml
      IBF-build processed 2 sequences (0.000134 Mbp) in 0.0107952 seconds (11.116 Kseq/m, 0.744775 Mbp/m)
       - 2 sequences in 2 bins were written to the IBF
      Trying to connect to MinKNOW
      Host : localhost
      Port : 9502
      Connecting to MinKNOW using the token: f7ca0499-24e7-4172-9fd7-5a1e1943f995
      Connection successfully established!
      Waiting for device to start sequencing!
      Please start the sequencing run now!
      Sequencing has begun. Starting live signal processing!
      Connecting to Guppy basecall server on address : ipc:///tmp/.guppy/5555
      [guppy/error] basecall_service::BasecallClient::worker_loop: Connection error. [timed_out] Timeout waiting for reply to request: LOAD_CONFIG
      [timed_out] Timeout waiting for reply to request: LOAD_CONFIG
      Real time : 432.156 sec
      CPU time  : 0.1894 sec
      Peak RSS  : 31 MByte

 Any more suggestions? Thanks

**Comment by JensUweUlrich** [comment]
Can you please tell me which Guppy version you are currently using on your machine?
