### ISSUE TITLE
Guppy connection error

### ISSUE THREAD

**Issue by ylang0825** [JensUweUlrich/ReadBouncer#66]
Hi, thanks for your great job! When I'm to use it, I also face the guppy connection problem when using guppy6.4.6 and MinKNOW core 5.4.3. When I run as root, the problem is sill there. By the way, I can run readfish with guppy6.4.6 as root, so I guess my Guppy is working well.

Below is the output:

IBF-build processed 51 sequences (12.8433 Mbp) in 0.812882 seconds (3.76438 Kseq/m, 947.983 Mbp/m)
 - 51 sequences in 159 bins were written to the IBF
Trying to connect to MinKNOW
Host : localhost
Port : 9502
Connecting to MinKNOW using the token: e9696685-b3af-4c01-ae5e-e014dc721f35
Connection successfully established!
Waiting for device to start sequencing!
Please start the sequencing run now!
Sequencing has begun. Starting live signal processing!
Connecting to Guppy basecall server on address : ipc:///tmp/.guppy/5555
[guppy/error] basecall_service::BasecallClient::worker_loop: Connection error. [bad_reply] Could not interpret message from server for request: LOAD_CONFIG. Reply: INVALID_PROTOCOL
[bad_reply] Could not interpret message from server for request: LOAD_CONFIG. Reply: INVALID_PROTOCOL
Real time : 0.909562 sec
CPU time  : 0.890361 sec
Peak RSS  : 81 MByte

My config is like this:

caller="Guppy"
host="ipc:///tmp/.guppy"
port=5555
config="dna_r9.4.1_450bps_fast"

I noticed that the developer has specific binary for guppy6.2. But I tried that and still failed. Could this be solved if there is a binary for guppy6.4?

Since Guppy failed, I also tried DeepNano. It seems that ReadBouncer is running but I did not see a purple bar in MinKNOW reflecting adaptive sampling. I use 16G memory and 8-core CPU. Could this be caused by CPU's insufficient power?

Below is the output and I can see ReadBouncer is running:
IBF-build processed 51 sequences (12.8433 Mbp) in 0.779194 seconds (3.92714 Kseq/m, 988.969 Mbp/m)
 - 51 sequences in 159 bins were written to the IBF
Trying to connect to MinKNOW
Host : localhost
Port : 9502
Connecting to MinKNOW using the token: e9696685-b3af-4c01-ae5e-e014dc721f35
Connection successfully established!
Waiting for device to start sequencing!
Please start the sequencing run now!
Sequencing has begun. Starting live signal processing!
Start receiving live signals thread
Start basecalling thread
Start read classification thread
Start sending unblock messages thread
ReadBouncer/data/rnn48.txt
ReadBouncer/data/rnn48.txt
ReadBouncer/data/rnn48.txt
ReadBouncer/data/rnn48.txt
ReadBouncer/data/rnn48.txt
ReadBouncer/data/rnn48.txt
ReadBouncer/data/rnn48.txt
ReadBouncer/data/rnn48.txt

I have another question. Could ReadBouncer run with half of the channels as the adaptive group and the left as the control group?

Thank you very much!

**Comment by JensUweUlrich** [comment]
I'm sorry for not getting back to you earlier. I'm occupied with other projects at the moment. However, I managed to provide binaries for ReadBouncer with Guppy 6.4 support, which you can find [here](https://github.com/JensUweUlrich/ReadBouncer/releases/tag/v1.2.2). This should fix your problems on that side. I don't know why base-calling with DeepNano did not work. Usually, it's enough to use 3 or 4 base-calling threads. Could you let me know if you recognized any error messages in the log files?

Regarding your question, you can specify the channels parameter in the Minknow section of the config file to use only half of the channels. The following will tell ReadBouncer to apply adaptive sampling only to the first 256 channels of the flowcell.
```
[MinKNOW]
..
channels           = [1,256]
```

Best
Jens
